# Generated by Django 5.2.15 on 2026-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='lugar')),
                ('platform', models.CharField(blank=True, choices=[('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('zoom', 'Zoom'), ('presencial', 'Presencial')], max_length=20, verbose_name='plataforma')),
                ('meet_url', models.URLField(blank=True, verbose_name='enlace de reunión')),
                ('tag', models.CharField(choices=[('obligatoria', 'Obligatoria'), ('recomendada', 'Recomendada'), ('solo_socios', 'Solo socios'), ('comercial', 'Comercial')], default='recomendada', max_length=20, verbose_name='tipo')),
                ('reminder', models.BooleanField(default=True, verbose_name='recordatorio activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['date', 'time'],
            },
        ),
    ]
