# Generated by Django 5.2.15 on 2026-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('percent', models.PositiveSmallIntegerField(default=15, verbose_name='porcentaje')),
                ('where', models.CharField(default='En carnicerías y puntos aliados Lomarosa', max_length=200, verbose_name='válido en')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido hasta')),
                ('max_redemptions', models.PositiveIntegerField(default=20, verbose_name='canjes máximos')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=200, verbose_name='establecimiento')),
                ('date', models.DateField(verbose_name='fecha')),
                ('status', models.CharField(choices=[('canjeado', 'Canjeado'), ('pendiente', 'Pendiente'), ('expirado', 'Expirado')], default='canjeado', max_length=10, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'canje',
                'verbose_name_plural': 'canjes',
                'ordering': ['-date'],
            },
        ),
    ]
