# Generated by Django 5.2.15 on 2026-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('category', models.CharField(choices=[('noticias', 'Noticias'), ('circular', 'Circular'), ('evento', 'Bogotá Eats'), ('marketing', 'Marketing')], default='noticias', max_length=20, verbose_name='categoría')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='resumen')),
                ('body', models.TextField(blank=True, verbose_name='contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='imagen')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='posts/pdf/', verbose_name='PDF')),
                ('glyph', models.CharField(default='L', max_length=2, verbose_name='glifo')),
                ('reactions', models.PositiveIntegerField(default=0, verbose_name='reacciones')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='propuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado')),
            ],
            options={
                'verbose_name': 'propuesta',
                'verbose_name_plural': 'propuestas',
                'ordering': ['-created_at'],
            },
        ),
    ]
