# Generated by Django 5.2.15 on 2026-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='texto')),
                ('link_label', models.CharField(blank=True, max_length=60, verbose_name='texto del enlace')),
                ('link_url', models.CharField(blank=True, max_length=200, verbose_name='destino del enlace')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('zone', models.CharField(blank=True, max_length=120, verbose_name='zona')),
                ('emoji', models.CharField(default='🥩', max_length=4, verbose_name='emoji')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='calificación')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'punto aliado',
                'verbose_name_plural': 'puntos aliados',
                'ordering': ['order', 'name'],
            },
        ),
    ]
