# Generated by Django 5.2.15 on 2026-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='PDF')),
                ('size_label', models.CharField(blank=True, max_length=20, verbose_name='tamaño')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('oficial', 'Oficial'), ('activo', 'Activo')], default='vigente', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
